config/routes.rb
Rails.application.routes.draw do

  post 'cart_products' => "cart_products#create"
  get 'cart_products/:id' => "cart_products#show", as: "cart_product"
  delete 'cart_products/:id' => "cart_products#destroy"
  post 'cart_products/:id/add' => "cart_products#add_quantity", as: "cart_product_add"
  post 'cart_products/:id/reduce' => "cart_products#reduce_quantity", as: "cart_product_reduce"
  devise_for :users
  resources :users, :only => [:show]
  resources :products

  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  get 'products/welcome'
  root 'products#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_products, dependent: :destroy
  has_many :products, :through => :cart_products

  def sub_total
    sum = 0
    self.cart_products.each do |cart_product|
      sum+= cart_product.total_price
    end
    return sum
  end
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  has_one_attached :avatar

  def total_price
    self.quantity * self.product.price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :avatar
  has_many :cart_products, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_one :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :current_cart

  protected

    def after_sign_in_path_for(resource)
      root_path
    end

    def after_sign_out_path_for(resource)
      root_path
    end

  private
    def current_cart
      if session[:cart_id]
        cart = Cart.find_by(:id => session[:cart_id])
        if cart.present?
          @current_cart = cart
        else
          session[:cart_id] = nil
        end
      end

      if session[:cart_id] == nil
        @current_cart = Cart.create
        session[:cart_id] = @current_cart.id
      end
    end
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController

  # POST /cart_products or /cart_products.json
  def create
    chosen_product = Product.find(params[:product_id])
    current_cart = @current_cart

    if current_cart.products.include?(chosen_product)
      @cart_product = current_cart.cart_products.find_by(:product_id => chosen_product)
      @cart_product.quantity += 1
    else
      @cart_product = CartProduct.new
      @cart_product.cart = current_cart
      @cart_product.product = chosen_product
    end

    @cart_product.save
    redirect_to cart_path(current_cart)
  end

  # DELETE /cart_products/1 or /cart_products/1.json
  def destroy
    @cart_product = CartProduct.find(params[:id])
    @cart_product.destroy
    redirect_to cart_path(@current_cart)
  end

  def add_quantity
    @cart_product = CartProduct.find(params[:id])
    @cart_product.quantity += 1
    @cart_product.save
    redirect_to cart_path(@current_cart)
  end

  def reduce_quantity
    @cart_product = CartProduct.find(params[:id])
    if @cart_product.quantity > 1
      @cart_product.quantity -= 1
    end
    @cart_product.save
    redirect_to cart_path(@current_cart)
  end

  private
    def cart_product_params
      params.require(:cart_product).permit(:quantity, :product_id, :cart_id)
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  # GET /carts/1 or /carts/1.json
  def show
    @cart = @current_cart
  end

  # POST /carts or /carts.json
  def create
    respond_to do |format|
      if @cart.create
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to cart_path(@cart.id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  # GET /products or /products.json
  def index
    if params[:brand] && params[:gender]
      @selection = params[:brand].capitalize
      @products = Product.where(:brand => params[:brand], :gender => params[:gender])
    elsif params[:style] && params[:gender]
      @selection = params[:style].capitalize
      @products = Product.where(:style => params[:style], :gender => params[:gender])
    elsif params[:colour] && params[:gender]
      @selection = params[:colour].capitalize
      @products = Product.where(:colour => params[:colour], :gender => params[:gender])
    elsif params[:size]
      @selection = params[:size].capitalize
      @products = Product.where(:size => params[:size])
    elsif params[:gender]
      @selection = params[:gender].capitalize
      @products = Product.where(:gender => params[:gender])
    else
      @selection = "All Products"
      @products = Product.all
    end
  end


  def welcome
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product = Product.find(params[:id])
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :gender, :brand, :style, :colour, :size, :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = current_user
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/show.html.erb
<div class="container mt-5">
  <%if @cart.sub_total>0%>
    <ul>
      <% @cart.cart_products.each do |cart_product| %>
        <div class="container-flex mt-2">
          <div class="card">
            <div class="row g-0">
              <div class="col-md-8">
                <div class="container-flex">
                  <div class="row">
                    <div class="img"><%= image_tag(cart_product.product.avatar, :size => 300) %></div>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="p-3 right-side">
                  <h3><%= cart_product.product.title %></h3></span>
                  <h3>£<%=cart_product.product.price%></h3>
                  <div class="row">
                    <div class="col">
                      <%= button_to "Add one", cart_product_add_path(:id => cart_product), method: "post", class: 'btn btn-outline-dark' %>
                    </div>
                    <div class="col">
                      <%= button_to "Reduce one", cart_product_reduce_path(:id => cart_product), method: "post", class: 'btn btn-outline-dark' %>
                    </div>
                    <div class="col">
                      <%= button_to "Remove item", cart_product_path(cart_product), method: :delete, class: 'btn btn-outline-dark' %>
                    </div>
                  </div>

                  <div class="row mt-4 justify-content-end">
                    <div class="col-6">
                      <h4>Subtotal: £<%=cart_product.total_price%></h4>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <%end%>
      <div class="row justify-content-end">
        <div class="col-3">
          <div class="row justify-content-end">
            <h3>Sub total: £<%= @cart.sub_total %></h3>
          </div>
          <div class="row mt-1">
            <%= button_to "Proceed to checkout", cart_path(@current_cart), method: :delete, class: 'btn btn-outline-dark' %>
          </div>
          <div class="row mt-1">
            <%= button_to "Empty cart", cart_path(@current_cart), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-outline-dark' %>
          </div>
        </div>
      </div>
    </ul>
  <%else%>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="row">
        <h3>Your cart is empty! Check out our products <%= link_to "here! ", products_path %> </h3>
      </div>
    </div>
  </div>
  <%end%>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/products/_footer.html.erb
<!-- Remove the container if you want to extend the Footer to full width. -->

<footer style="background-color: #deded5;">
  <div class="container p-4">
    <div class="row align-items-center">
      <div class="col-lg-4 col-md-12 mb-4 ">
        <h5 class="mb-3 text-center" style="letter-spacing: 2px; ">Help and Support</h5>
        <ul class="list-unstyled mb-6 text-center">
          <li>
            <%=link_to "Customer Service", root_path, class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "FAQs", root_path, class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Returns and Exchanges", root_path, class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Shipping and Tracking", root_path, class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Size Chart", root_path, class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Store Locator", root_path, class: 'btn text-dark'%>
          </li>
        </ul>
      </div>
      <div class="col-lg-4 col-md-12 mb-4 ">
        <h5 class="mb-3 text-center" style="letter-spacing: 2px;">Shop</h5>
        <ul class="list-unstyled text-center">
          <li>
            <%=link_to "New Arrivals", products_path, class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Shop Men", products_path(gender: "men"), class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Shop Women", products_path(gender: "women"), class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Shop Kids", products_path(gender: "kids"), class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Bestsellers", products_path, class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Gift Guide", products_path, class: 'btn text-dark'%>
          </li>
        </ul>
      </div>

      <div class="col-lg-4 col-md-12 mb-4 ">
        <h5 class="mb-3 text-center" style="letter-spacing: 2px;">About Us</h5>
        <ul class="list-unstyled text-center">
          <li>
            <%=link_to "Who We Are", root_path, class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Sustainability and Inclusivity", root_path, class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Blog", root_path, class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Careers", root_path, class: 'btn text-dark'%>
          </li>
          <li>
            <%=link_to "Contact Us", root_path, class: 'btn text-dark'%>
          </li>
        </ul>

        <div class="container">
          <div class="row">
            <div class="col">
              <img class="img" src="/products/assets/images/social_icons/1.png">
            </div>
            <div class="col">
              <img class="img" src="/products/assets/images/social_icons/2.png">
            </div>
            <div class="col">
              <img class="img" src="/products/assets/images/social_icons/3.png">
            </div>
            <div class="col">
              <img class="img" src="/products/assets/images/social_icons/4.png">
            </div>
            <div class="col">
              <img class="img" src="/products/assets/images/social_icons/5.png">
            </div>
            <div class="col">
              <img class="img" src="/products/assets/images/social_icons/6.png">
            </div>
          </div>
        </div>

      </div>
    </div>
    <div class="row align-items-center">
        <div class="text-center p-3 border-top border-white">
          <p class="text-dark">(012) 123-4567</p>
          <p class="text-dark">1337 Someplace Street</p>
          <p class="text-dark">A4, London WC2N 5DU, UK</p>
        </div>
      </div>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-dark" href="/">Golden Shoe</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- End of .container -->

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_area :gender %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_area :brand %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_area :style %>
  </div>

  <div class="field">
    <%= form.label :colour %>
    <%= form.text_area :colour %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.number_field :size %>
  </div>

  <div class="field">
    <%= form.label "Photo" %>
    <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_header.html.erb
<nav class="navbar navbar-expand-md border-top navbar-light bg-light h4">
  <div class="container-fluid">
      <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
          <ul class="navbar-nav me-auto">
              <a class="navbar-brand" href="/">
                <img src="/products/assets/images/logos/1.png" width="150" alt="Golden Shoe">
              </a>
          </ul>
      </div>
    <div class="mx-auto order-0">
        <ul class="navbar-nav ms-auto">
          <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> New Arrivals </a>
                <ul class="dropdown-menu dropdown-menu-right text-center" aria-labelledby="navbarScrollingDropdown">
                  <li><%=link_to 'All', products_path, :class => 'dropdown-item'%></li>
                  <li><%=link_to 'Women', products_path(gender: "women"), :class => 'dropdown-item'%></li>
                  <li><%=link_to 'Men', products_path(gender: "men"), :class => 'dropdown-item'%></li>
                  <li><%=link_to 'Kids', products_path(gender: "kids"), :class => 'dropdown-item'%></li>
                </ul>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-dark" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Women </a>
              <ul class="dropdown-menu text-center dropdown-menu-right" aria-labelledby="navbarScrollingDropdown" style="width: 30em;">
                <div class="dropdown-col" style="display: inline-block; width: 32%; vertical-align: top">
                  <h5 class="text-center">Shoes</h5>
                  <ul class="list-unstyled mb-6 text-center">
                    <li><%=link_to 'All Shoes', products_path(gender: "women"), :class => 'dropdown-item'%></li>
                    <li><%=link_to 'New Arrivals', products_path(gender: "women"), :class => 'dropdown-item'%></li>
                  </ul>
                </div>
                <div class="dropdown-col" style="display: inline-block; width: 32%;">
                  <h5 class="text-center">By Brand</h5>
                  <ul class="list-unstyled mb-6 text-center">
                    <%Product.where(gender: "women").pluck(:brand).uniq.each do |brand|%>
                      <li><%=link_to brand, products_path(brand: brand, gender: "women"), :class => 'dropdown-item'%></li>
                    <%end%>
                    </ul>
                  </li>
                </div>
                <div class="dropdown-col" style="display: inline-block; width: 32%; vertical-align: top">
                  <h5 class="text-center">By Style</h5>
                  <ul class="list-unstyled mb-6 text-center">
                    <%Product.where(gender: "women").pluck(:style).uniq.each do |style|%>
                      <li><%=link_to style, products_path(style: style, gender: "women"), :class => 'dropdown-item'%></li>
                    <%end%>
                    </ul>
                  </li>
                </div>
              </ul>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-dark" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Men </a>
              <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarScrollingDropdown" style="width: 30em;">
                <div class="dropdown-col" style="display: inline-block; width: 32%; vertical-align: top">
                  <h5 class="text-center">Shoes</h5>
                  <ul class="list-unstyled mb-6 text-center">
                    <li><%=link_to 'All Shoes', products_path(gender: "men"), :class => 'dropdown-item'%></li>
                    <li><%=link_to 'New Arrivals', products_path(gender: "men"), :class => 'dropdown-item'%></li>
                  </ul>
                </div>
                <div class="dropdown-col" style="display: inline-block; width: 32%; vertical-align: top">
                  <h5 class="text-center">By Brand</h5>
                    <ul class="list-unstyled mb-6 text-center">
                      <%Product.where(gender: "men").pluck(:brand).uniq.each do |brand|%>
                        <li><%=link_to brand, products_path(brand: brand, gender: "men"), :class => 'dropdown-item'%></li>
                      <%end%>
                    </ul>
                  </li>
                </div>
                <div class="dropdown-col" style="display: inline-block; width: 32%; vertical-align: top">
                  <h5 class="text-center">By Style</h5>
                    <ul class="list-unstyled mb-6 text-center">
                      <%Product.where(gender: "men").pluck(:style).uniq.each do |style|%>
                        <li><%=link_to style, products_path(style: style, gender: "men"), :class => 'dropdown-item'%></li>
                      <%end%>
                    </ul>
                  </li>
                </div>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-dark" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> Kids </a>
              <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarScrollingDropdown" style="width: 30em;">
                <div class="dropdown-col" style="display: inline-block; width: 32%; vertical-align: top">
                  <h5 class="text-center">Shoes</h5>
                  <ul class="list-unstyled mb-6 text-center">
                    <li><%=link_to 'All Shoes', products_path(:gender=>("kids")), :class => 'dropdown-item'%></li>
                    <li><%=link_to 'New Arrivals', products_path(:gender=>("kids")), :class => 'dropdown-item'%></li>
                  </ul>
                </div>
                <div class="dropdown-col" style="display: inline-block; width: 32%; vertical-align: top">
                  <h5 class="text-center">By Brand</h5>
                    <ul class="list-unstyled mb-6 text-center">
                      <%Product.where(gender: "kids").pluck(:brand).uniq.each do |brand|%>
                        <li><%=link_to brand, products_path(brand: brand, gender: "kids"), :class => 'dropdown-item'%></li>
                      <%end%>
                    </ul>
                  </li>
                </div>
                <div class="dropdown-col" style="display: inline-block; width: 32%; vertical-align: top">
                  <h5 class="text-center">By Style</h5>
                    <ul class="list-unstyled mb-6 text-center">
                      <%Product.where(gender: "kids").pluck(:style).uniq.each do |style|%>
                        <li><%=link_to style, products_path(style: style, gender: "kids"), :class => 'dropdown-item'%></li>
                      <%end%>
                    </ul>
                  </li>
                </div>
              </ul>
            </li>
        </div>
      </div>

      <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item">
              <button type="button" class="btn btn-default">
                <% if user_signed_in?%>
                  <%=link_to image_tag("/products/assets/images/social_icons/user.png", :width => 30), user_path(current_user.id), :class => 'dropdown-item'%>
                <% else %>
                  <%=link_to image_tag("/products/assets/images/social_icons/user.png", :width => 30), new_user_session_path, :class => 'dropdown-item'%>
                <% end %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-default">
                <%=link_to image_tag("/products/assets/images/social_icons/cart.png", :width => 30), cart_path(@current_cart), :class => 'dropdown-item'%>
              </button>
            </li>
            <li>
              <div class="input-group">
                <input type="text" class="form-control form-control-md" placeholder="Search">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit">
                    <img src="/products/assets/images/social_icons/search.png" width="20">
                  </button>
                </div>
              </div>
            </li>
          </ul>
      </div>
  </div>
</nav>

app/views/products/_product_card.html.erb
<div class="container">
  <div class="row-md-4">
    <div class="product-item">
      <div class="pi-img-wrapper">
        <% if product.avatar.attached? %>
          <%=link_to image_tag(product.avatar, :size => 300), product_path(product.id), :class => 'dock-item'%>
        <%end%>
      </div>
      <h4 class="mb-1" style="letter-spacing: 2px;"><%=product.title%></h4>
      <h5 class="mb-1" style="letter-spacing: 2px;">£<%=product.price%></h5>
    </div>
      <%=button_to "Add to cart", cart_products_path(:product_id => product.id), class: 'btn btn-outline-dark', method: "post"%>
  </div>
</div>
<br/>
<br/>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container mt-5 mb-5">
  <div class="card border-0">
    <div class="row g-0">
      <div class="col-md-8">
        <div class="container-flex">
          <div class="row">
            <div class="img"><%= image_tag(@product.avatar, :size => 850) %></div>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="p-3 right-side">
          <h3><%= @product.title %></h3></span>
          <h3>£<%=@product.price%></h3>
          <div class="mt-5"> <span class="fw-bold">Colour</span>
            <select class="form-select" aria-label="colour">
              <option selected>Black</option>
              <option value="1">Green</option>
              <option value="2">White</option>
              <option value="3">Pink</option>
            </select>
          </div>
          <div class="mt-3 mb-2"> <span class="fw-bold text">Size</span>
            <select class="form-select" aria-label="size">
              <option selected>4</option>
              <option value="1">5</option>
              <option value="2">6</option>
              <option value="3">7</option>
            </select>
          </div>
          <%=button_to "Add to cart", cart_products_path(:product_id => @product.id), class: 'btn btn-outline-dark', method: "post"%>
        </div>

        <div class="accordion" id="accordion">
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
              <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Information
              </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                <%= @product.description %>
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                Sizing Guide
              </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla cursus turpis ac libero maximus facilisis. Morbi ultrices sollicitudin enim et suscipit. Aliquam at facilisis orci. Quisque a diam odio. 
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <h2 class="accordion-header" id="headingThree">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                Shipping and Returns
              </button>
            </h2>
            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
              <div class="accordion-body">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla cursus turpis ac libero maximus facilisis. Morbi ultrices sollicitudin enim et suscipit. Aliquam at facilisis orci. Quisque a diam odio. In sapien felis, ultrices a consequat et, sodales eu neque. 
              </div>
            </div>
          </div>
        </div>











        
      </div>
    </div>
  </div>
</div>